version: '3.8'
services:
  dev-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'testing'
      MYSQL_DATABASE: 'media'
      MYSQL_PASSWORD: 'testing'
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - db

networks:
  db:
    driver: bridge